config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :enrollments, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :enrollments
    has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :enrollments
    has_many :courses, through: :enrollments
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

app/views/enrollments/destroy.html.erb
<h1>Enrollments#destroy</h1>
<p>Find me in app/views/enrollments/destroy.html.erb</p>

app/views/enrollments/index.html.erb
<h1>Enrollments#index</h1>
<p>Find me in app/views/enrollments/index.html.erb</p>

app/views/enrollments/new.html.erb
<h1>Enrollments#new</h1>
<p>Find me in app/views/enrollments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Students Index</h1>
<%= button_to "Add new student", new_student,path, method: :get %>

<ul>
    <% @students.each do |student| %>
        <li>
        <%= link_to student.name, student_path(student)%>
        </li>
</ul>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>